"""Initial tables - Jobs, URLCheckResult, ProcessingLog, SystemMetric

Revision ID: 072f38af4d19
Revises: 
Create Date: 2025-12-30 22:07:02.487559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '072f38af4d19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=True),
    sa.Column('max_concurrent', sa.Integer(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('verify_ssl', sa.Boolean(), nullable=True),
    sa.Column('total_urls', sa.Integer(), nullable=True),
    sa.Column('processed_urls', sa.Integer(), nullable=True),
    sa.Column('active_urls', sa.Integer(), nullable=True),
    sa.Column('inactive_urls', sa.Integer(), nullable=True),
    sa.Column('error_urls', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('output_file', sa.String(length=255), nullable=True),
    sa.Column('output_format', sa.String(length=10), nullable=True),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_completed', 'jobs', ['completed_at'], unique=False)
    op.create_index('idx_job_status_created', 'jobs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_filename'), 'jobs', ['filename'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('system_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('cpu_count', sa.Integer(), nullable=True),
    sa.Column('memory_total', sa.Integer(), nullable=True),
    sa.Column('memory_available', sa.Integer(), nullable=True),
    sa.Column('memory_percent', sa.Float(), nullable=True),
    sa.Column('disk_total', sa.Integer(), nullable=True),
    sa.Column('disk_free', sa.Integer(), nullable=True),
    sa.Column('disk_percent', sa.Float(), nullable=True),
    sa.Column('active_jobs', sa.Integer(), nullable=True),
    sa.Column('total_jobs', sa.Integer(), nullable=True),
    sa.Column('urls_per_second', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_metric_timestamp', 'system_metrics', ['timestamp'], unique=False)
    op.create_index(op.f('ix_system_metrics_timestamp'), 'system_metrics', ['timestamp'], unique=False)
    op.create_table('processing_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=True),
    sa.Column('function', sa.String(length=100), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_log_job_time', 'processing_logs', ['job_id', 'timestamp'], unique=False)
    op.create_index('idx_log_level', 'processing_logs', ['level'], unique=False)
    op.create_index(op.f('ix_processing_logs_job_id'), 'processing_logs', ['job_id'], unique=False)
    op.create_index(op.f('ix_processing_logs_timestamp'), 'processing_logs', ['timestamp'], unique=False)
    op.create_table('url_check_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('normalized_url', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ERROR', 'TIMEOUT', name='urlstatus'), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=True),
    sa.Column('final_url', sa.String(length=2048), nullable=True),
    sa.Column('redirect_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_category', sa.String(length=50), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('ssl_verified', sa.Boolean(), nullable=True),
    sa.Column('ssl_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_result_checked', 'url_check_results', ['checked_at'], unique=False)
    op.create_index('idx_result_job_status', 'url_check_results', ['job_id', 'status'], unique=False)
    op.create_index('idx_result_url', 'url_check_results', ['url'], unique=False, mysql_length=255)
    op.create_index(op.f('ix_url_check_results_checked_at'), 'url_check_results', ['checked_at'], unique=False)
    op.create_index(op.f('ix_url_check_results_job_id'), 'url_check_results', ['job_id'], unique=False)
    op.create_index(op.f('ix_url_check_results_normalized_url'), 'url_check_results', ['normalized_url'], unique=False)
    op.create_index(op.f('ix_url_check_results_status'), 'url_check_results', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_check_results_status'), table_name='url_check_results')
    op.drop_index(op.f('ix_url_check_results_normalized_url'), table_name='url_check_results')
    op.drop_index(op.f('ix_url_check_results_job_id'), table_name='url_check_results')
    op.drop_index(op.f('ix_url_check_results_checked_at'), table_name='url_check_results')
    op.drop_index('idx_result_url', table_name='url_check_results', mysql_length=255)
    op.drop_index('idx_result_job_status', table_name='url_check_results')
    op.drop_index('idx_result_checked', table_name='url_check_results')
    op.drop_table('url_check_results')
    op.drop_index(op.f('ix_processing_logs_timestamp'), table_name='processing_logs')
    op.drop_index(op.f('ix_processing_logs_job_id'), table_name='processing_logs')
    op.drop_index('idx_log_level', table_name='processing_logs')
    op.drop_index('idx_log_job_time', table_name='processing_logs')
    op.drop_table('processing_logs')
    op.drop_index(op.f('ix_system_metrics_timestamp'), table_name='system_metrics')
    op.drop_index('idx_metric_timestamp', table_name='system_metrics')
    op.drop_table('system_metrics')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_filename'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_index('idx_job_status_created', table_name='jobs')
    op.drop_index('idx_job_completed', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
